FROM apache/airflow:3.2.1

USER root
RUN apt-get update && apt-get install -y gcc && apt-get clean

USER airflow
RUN pip install --no-cache-dir \
    loguru==0.7.2 \
    psycopg2-binary \
    sqlalchemy>=2.0 \
    python-dotenv==1.0.0 \
    requests==2.31.0